import inquirer from 'inquirer';
import chalk from 'chalk';
import { loadConfig, updateConfig, CONFIG_FILE } from '../config.js';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const ENV_FILE = join(homedir(), '.intelwatch', '.env');

// ─── Banner ────────────────────────────────────────────────────────────────────

function printBanner() {
  console.log();
  console.log(chalk.cyan('  ╔══════════════════════════════════════════════════╗'));
  console.log(chalk.cyan('  ║') + chalk.bold.white('  Intelwatch Setup Wizard                        ') + chalk.cyan('║'));
  console.log(chalk.cyan('  ║') + chalk.gray('  Configure your API keys and search provider    ') + chalk.cyan('║'));
  console.log(chalk.cyan('  ╚══════════════════════════════════════════════════╝'));
  console.log();
}

// ─── Mask helper ───────────────────────────────────────────────────────────────

function mask(key) {
  if (!key || key.length < 8) return key ? '••••••••' : '';
  return key.slice(0, 4) + '••••' + key.slice(-4);
}

// ─── Detect existing values ────────────────────────────────────────────────────

function detectCurrentValues() {
  const config = loadConfig();
  const envKeys = loadEnvFile();

  const ai = config.ai || {};
  const search = config.search || {};

  return {
    aiProvider: ai.provider || process.env.AI_PROVIDER || envKeys.AI_PROVIDER || '',
    aiApiKey: ai.api_key || process.env.GEMINI_API_KEY || process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY || process.env.OPENROUTER_API_KEY || envKeys.GEMINI_API_KEY || envKeys.OPENAI_API_KEY || envKeys.ANTHROPIC_API_KEY || envKeys.OPENROUTER_API_KEY || '',
    aiModel: ai.model || '',
    pappersKey: process.env.PAPPERS_API_KEY || envKeys.PAPPERS_API_KEY || search.pappers_api_key || '',
    searchProvider: search.provider || process.env.SEARCH_PROVIDER || envKeys.SEARCH_PROVIDER || '',
    searchKey: search.api_key || process.env.SERPAPI_KEY || process.env.SERPER_API_KEY || process.env.BRAVE_API_KEY || envKeys.SERPER_API_KEY || envKeys.BRAVE_API_KEY || '',
    searxngUrl: search.searxng_url || process.env.SEARXNG_URL || envKeys.SEARXNG_URL || '',
  };
}

// ─── .env file helpers ─────────────────────────────────────────────────────────

function loadEnvFile() {
  if (!existsSync(ENV_FILE)) return {};
  try {
    const raw = readFileSync(ENV_FILE, 'utf8');
    const result = {};
    for (const line of raw.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
      result[key] = val;
    }
    return result;
  } catch {
    return {};
  }
}

function saveEnvFile(values) {
  const lines = [
    '# Intelwatch environment configuration',
    '# Generated by `intelwatch setup`',
    '',
  ];
  for (const [key, val] of Object.entries(values)) {
    if (val) {
      lines.push(`${key}="${val}"`);
    }
  }
  lines.push('');
  writeFileSync(ENV_FILE, lines.join('\n'), 'utf8');
}

// ─── Main wizard ───────────────────────────────────────────────────────────────

export async function runSetup() {
  printBanner();

  const current = detectCurrentValues();

  // ── Step 1: AI Provider & Key ──────────────────────────────────────────────

  console.log(chalk.bold.white('  Step 1 / 3 : AI Provider'));
  console.log(chalk.gray('  Required for ai-summary, pitch, discover --ai, profile --ai'));
  console.log();

  const aiAnswers = await inquirer.prompt([
    {
      type: 'list',
      name: 'aiProvider',
      message: 'Which AI provider do you want to use?',
      choices: [
        { name: 'Google Gemini (recommended, best value)', value: 'google' },
        { name: 'OpenAI', value: 'openai' },
        { name: 'Anthropic', value: 'anthropic' },
        { name: 'OpenRouter (multi-provider gateway)', value: 'openrouter' },
        { name: 'Skip — I\'ll use local Ollama only', value: 'skip' },
      ],
      default: current.aiProvider || 'google',
    },
    {
      type: 'input',
      name: 'aiApiKey',
      message: (answers) => {
        if (answers.aiProvider === 'skip') return 'Skipped';
        const labels = { google: 'Gemini', openai: 'OpenAI', anthropic: 'Anthropic', openrouter: 'OpenRouter' };
        return `${labels[answers.aiProvider]} API Key:`;
      },
      when: (answers) => answers.aiProvider !== 'skip',
      default: current.aiApiKey || undefined,
      filter: (val) => val.trim(),
      validate: (val) => val.length > 0 ? true : 'API key is required (or press Ctrl+C to skip)',
    },
    {
      type: 'input',
      name: 'aiModel',
      message: 'Default model (leave empty for provider default):',
      when: (answers) => answers.aiProvider !== 'skip',
      default: current.aiModel || undefined,
    },
  ]);

  // ── Step 2: Pappers API Key ────────────────────────────────────────────────

  console.log();
  console.log(chalk.bold.white('  Step 2 / 3 : Company Data'));
  console.log(chalk.gray('  Used by profile, compare — SIREN/SIRET lookups'));
  console.log(chalk.yellow('  ⚠  Without a Pappers key, intelwatch falls back to free DataGouv APIs'));
  console.log(chalk.gray('     (recherche-entreprises.api.gouv.fr, BODACC) — slower, less detailed.'));
  console.log();

  const pappersAnswers = await inquirer.prompt([
    {
      type: 'input',
      name: 'pappersKey',
      message: 'Pappers API Key (optional — press Enter to skip):',
      default: current.pappersKey || undefined,
      filter: (val) => val.trim(),
    },
  ]);

  // ── Step 3: Web Search ─────────────────────────────────────────────────────

  console.log();
  console.log(chalk.bold.white('  Step 3 / 3 : Web Search'));
  console.log(chalk.gray('  Used by discover, track keyword, track brand, track person'));
  console.log();

  const searchAnswers = await inquirer.prompt([
    {
      type: 'list',
      name: 'searchProvider',
      message: 'Which search backend do you want to use?',
      choices: [
        { name: 'SearXNG (self-hosted, free)', value: 'searxng' },
        { name: 'Serper.dev (Google SERP API)', value: 'serper' },
        { name: 'Brave Search API', value: 'brave' },
        { name: 'Skip — I\'ll configure later', value: 'skip' },
      ],
      default: current.searchProvider || 'searxng',
    },
    {
      type: 'input',
      name: 'searxngUrl',
      message: 'SearXNG instance URL:',
      when: (answers) => answers.searchProvider === 'searxng',
      default: current.searxngUrl || 'http://localhost:8888',
      validate: (val) => {
        if (!val.trim()) return 'URL is required';
        try { new URL(val.trim()); return true; } catch { return 'Invalid URL'; }
      },
      filter: (val) => val.trim().replace(/\/+$/, ''),
    },
    {
      type: 'input',
      name: 'searchApiKey',
      message: (answers) => {
        const labels = { serper: 'Serper', brave: 'Brave' };
        return `${labels[answers.searchProvider]} API Key:`;
      },
      when: (answers) => ['serper', 'brave'].includes(answers.searchProvider),
      default: current.searchKey || undefined,
      filter: (val) => val.trim(),
      validate: (val) => val.length > 0 ? true : 'API key is required',
    },
  ]);

  // ── Save everything ────────────────────────────────────────────────────────

  console.log();
  console.log(chalk.cyan('  Saving configuration...'));

  // Build config.yml updates
  const configUpdates = {};

  if (aiAnswers.aiProvider && aiAnswers.aiProvider !== 'skip') {
    configUpdates.ai = {
      provider: aiAnswers.aiProvider,
      api_key: aiAnswers.aiApiKey,
    };
    if (aiAnswers.aiModel) {
      configUpdates.ai.model = aiAnswers.aiModel;
    }
  }

  configUpdates.search = {
    provider: searchAnswers.searchProvider === 'skip' ? undefined : searchAnswers.searchProvider,
  };

  if (searchAnswers.searchProvider === 'searxng' && searchAnswers.searxngUrl) {
    configUpdates.search.searxng_url = searchAnswers.searxngUrl;
  }
  if (['serper', 'brave'].includes(searchAnswers.searchProvider) && searchAnswers.searchApiKey) {
    configUpdates.search.api_key = searchAnswers.searchApiKey;
  }

  if (pappersAnswers.pappersKey) {
    configUpdates.search.pappers_api_key = pappersAnswers.pappersKey;
  }

  // Clean up undefined
  for (const [k, v] of Object.entries(configUpdates.search)) {
    if (v === undefined) delete configUpdates.search[k];
  }

  updateConfig(configUpdates);

  // Also write ~/.intelwatch/.env for shell-level env vars
  const envValues = {};
  if (aiAnswers.aiProvider === 'google' && aiAnswers.aiApiKey) envValues.GEMINI_API_KEY = aiAnswers.aiApiKey;
  if (aiAnswers.aiProvider === 'openai' && aiAnswers.aiApiKey) envValues.OPENAI_API_KEY = aiAnswers.aiApiKey;
  if (aiAnswers.aiProvider === 'anthropic' && aiAnswers.aiApiKey) envValues.ANTHROPIC_API_KEY = aiAnswers.aiApiKey;
  if (aiAnswers.aiProvider === 'openrouter' && aiAnswers.aiApiKey) envValues.OPENROUTER_API_KEY = aiAnswers.aiApiKey;
  if (pappersAnswers.pappersKey) envValues.PAPPERS_API_KEY = pappersAnswers.pappersKey;
  if (searchAnswers.searchProvider === 'searxng' && searchAnswers.searxngUrl) envValues.SEARXNG_URL = searchAnswers.searxngUrl;
  if (searchAnswers.searchProvider === 'serper' && searchAnswers.searchApiKey) envValues.SERPER_API_KEY = searchAnswers.searchApiKey;
  if (searchAnswers.searchProvider === 'brave' && searchAnswers.searchApiKey) envValues.BRAVE_API_KEY = searchAnswers.searchApiKey;

  saveEnvFile(envValues);

  // ── Summary ────────────────────────────────────────────────────────────────

  console.log();
  console.log(chalk.green('  ✓ Configuration saved!'));
  console.log();
  console.log(chalk.white('  ┌─ Summary ──────────────────────────────────────┐'));

  if (aiAnswers.aiProvider && aiAnswers.aiProvider !== 'skip') {
    const providerLabels = { google: 'Google Gemini', openai: 'OpenAI', anthropic: 'Anthropic', openrouter: 'OpenRouter' };
    console.log(chalk.white('  │') + chalk.bold('  AI:') + `  ${providerLabels[aiAnswers.aiProvider]}  ${chalk.gray(mask(aiAnswers.aiApiKey))}`);
    if (aiAnswers.aiModel) {
      console.log(chalk.white('  │') + chalk.gray(`       Model: ${aiAnswers.aiModel}`));
    }
  } else {
    console.log(chalk.white('  │') + chalk.yellow('  AI:  Skipped (Ollama only)'));
  }

  if (pappersAnswers.pappersKey) {
    console.log(chalk.white('  │') + chalk.bold('  Pappers:') + `  ${chalk.gray(mask(pappersAnswers.pappersKey))}`);
  } else {
    console.log(chalk.white('  │') + chalk.bold('  Pappers:') + `  ${chalk.yellow('Not configured — using free DataGouv fallback')}`);
  }

  const searchLabels = { searxng: 'SearXNG', serper: 'Serper', brave: 'Brave' };
  if (searchAnswers.searchProvider && searchAnswers.searchProvider !== 'skip') {
    console.log(chalk.white('  │') + chalk.bold('  Search:') + `  ${searchLabels[searchAnswers.searchProvider]}`);
    if (searchAnswers.searxngUrl) {
      console.log(chalk.white('  │') + chalk.gray(`           ${searchAnswers.searxngUrl}`));
    }
    if (searchAnswers.searchApiKey) {
      console.log(chalk.white('  │') + chalk.gray(`           Key: ${mask(searchAnswers.searchApiKey)}`));
    }
  } else {
    console.log(chalk.white('  │') + chalk.yellow('  Search:  Not configured'));
  }

  console.log(chalk.white('  └─────────────────────────────────────────────────┘'));
  console.log();
  console.log(chalk.gray(`  Config:  ${CONFIG_FILE}`));
  console.log(chalk.gray(`  Env:     ${ENV_FILE}`));
  console.log(chalk.gray(`  Tip:     Source the .env in your shell or add it to .bashrc`));
  console.log();
}
